package MJL.tampilan;

import MJL.data.Login;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.border.Border;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;

/**
 *
 * @author WHOAMI
 */
public class BTampilanGabung extends javax.swing.JFrame {
    public Login authLogin;


    /**
     * Creates new form Login
     */
    
    public BTampilanGabung() {
        initComponents();
        
        authLogin = new Login();
        
        this.setLocationRelativeTo(null);
        
        Border label_border = BorderFactory.createMatteBorder(1, 3, 1, 3,new Color(0,0,153));
        LabelMinimize.setBorder(label_border);
        LabelExit.setBorder(label_border);
        
        Border label_regist = BorderFactory.createMatteBorder(0, 0, 1, 0,Color.WHITE);
        Disini.setBorder(label_regist);
        
        Border field_border = BorderFactory.createMatteBorder(1, 5, 1, 5,new Color(0,0,153));
        Tnamapengguna.setBorder(field_border);
        Tsandimasuk.setBorder(field_border);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    Login login = new Login();
    private void initComponents() {
        Panel1 = new javax.swing.JPanel();
        Panel2 = new javax.swing.JPanel(){
            public void paintComponent(Graphics g){
                ImageIcon img = new ImageIcon("src/main/java/MJL/gambar/Gambar1.jpg");
                Image i = img.getImage();
                g.drawImage(i, 0, 0, this);
            }
        }
        ;
        Label1 = new javax.swing.JLabel();
        Tnamapengguna = new javax.swing.JTextField();
        Label2 = new javax.swing.JLabel();
        Tsandimasuk = new javax.swing.JPasswordField();
        TombolMasuk = new javax.swing.JButton();
        Note1 = new javax.swing.JLabel();
        Panel3 = new javax.swing.JPanel();
        LabelJudul = new javax.swing.JLabel();
        LabelMinimize = new javax.swing.JLabel();
        LabelExit = new javax.swing.JLabel();
        Disini = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login User");
        setLocation(new java.awt.Point(0, 0));
        setUndecorated(true);
        setResizable(false);

        Panel1.setBackground(new java.awt.Color(0, 0, 153));

        Panel2.setBackground(new java.awt.Color(204, 204, 204));
        Panel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Label1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Label1.setText("NAMA PENGGUNA");
        Panel2.add(Label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 54, -1, -1));
        Panel2.add(Tnamapengguna, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 85, 270, -1));

        Label2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Label2.setText("SANDI");
        Panel2.add(Label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 125, -1, -1));
        Panel2.add(Tsandimasuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 156, 270, -1));

        TombolMasuk.setBackground(new java.awt.Color(0, 0, 153));
        TombolMasuk.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        TombolMasuk.setForeground(new java.awt.Color(255, 255, 255));
        TombolMasuk.setText("LOGIN");
        TombolMasuk.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TombolMasuk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TombolMasukMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TombolMasukMouseExited(evt);
            }
        });
        TombolMasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TombolMasukActionPerformed(evt);
            }
        });
        Panel2.add(TombolMasuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 188, 270, 35));

        Note1.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        Note1.setForeground(new java.awt.Color(255, 255, 255));
        Note1.setText("Tidak punya akun? klik");
        Note1.setFocusable(false);
        Note1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Note1.setPreferredSize(new java.awt.Dimension(271, 16));
        Panel2.add(Note1, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 235, 130, -1));

        Panel3.setBackground(new java.awt.Color(0, 0, 153));

        javax.swing.GroupLayout Panel3Layout = new javax.swing.GroupLayout(Panel3);
        Panel3.setLayout(Panel3Layout);
        Panel3Layout.setHorizontalGroup(
            Panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        Panel3Layout.setVerticalGroup(
            Panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        Panel2.add(Panel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, 270));

        LabelJudul.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        LabelJudul.setForeground(new java.awt.Color(0, 0, 153));
        LabelJudul.setText("MASUK");
        LabelJudul.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LabelJudulMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LabelJudulMouseExited(evt);
            }
        });
        Panel2.add(LabelJudul, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, -1, 30));

        LabelMinimize.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        LabelMinimize.setForeground(new java.awt.Color(0, 0, 153));
        LabelMinimize.setText(" -");
        LabelMinimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LabelMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelMinimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LabelMinimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LabelMinimizeMouseExited(evt);
            }
        });
        Panel2.add(LabelMinimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(391, 6, 25, 25));

        LabelExit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        LabelExit.setForeground(new java.awt.Color(0, 0, 153));
        LabelExit.setText(" X");
        LabelExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LabelExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LabelExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LabelExitMouseExited(evt);
            }
        });
        Panel2.add(LabelExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(422, 6, 28, 25));

        Disini.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        Disini.setForeground(new java.awt.Color(255, 255, 255));
        Disini.setText("di sini");
        Disini.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Disini.setFocusable(false);
        Disini.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Disini.setPreferredSize(new java.awt.Dimension(271, 16));
        Disini.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DisiniMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DisiniMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DisiniMouseExited(evt);
            }
        });
        Panel2.add(Disini, new org.netbeans.lib.awtextra.AbsoluteConstraints(291, 235, 34, -1));

        javax.swing.GroupLayout Panel1Layout = new javax.swing.GroupLayout(Panel1);
        Panel1.setLayout(Panel1Layout);
        Panel1Layout.setHorizontalGroup(
            Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel1Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(Panel2, javax.swing.GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE)
                .addGap(4, 4, 4))
        );
        Panel1Layout.setVerticalGroup(
            Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel1Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(Panel2, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
                .addGap(4, 4, 4))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();

        TombolMasuk.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                if(login.login(Tnamapengguna.getText(),Tsandimasuk.getText())){
                    if(login.admin(Tnamapengguna.getText())){
                        CTampilanAdmin tampilan = new CTampilanAdmin();
                        tampilan.setVisible(true);
                        tampilan.setLocationRelativeTo(null);
                        close();
                    } else {
                        FTampilanMenu tampilan = new FTampilanMenu();
                        tampilan.setVisible(true);
                        tampilan.setLocationRelativeTo(null);
                        close();
                    }
                }
            }
        });

    }// </editor-fold>//GEN-END:initComponents

    public void close(){
        this.dispose();
    }

    private void TombolMasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TombolMasukActionPerformed

    }//GEN-LAST:event_TombolMasukActionPerformed

    private void TombolMasukMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TombolMasukMouseEntered
        TombolMasuk.setBackground(Color.yellow);
        TombolMasuk.setForeground(Color.black);
    }//GEN-LAST:event_TombolMasukMouseEntered

    private void TombolMasukMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TombolMasukMouseExited
        TombolMasuk.setBackground(new Color(0,0,153));
        TombolMasuk.setForeground(Color.white);
    }//GEN-LAST:event_TombolMasukMouseExited

    private void LabelMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelMinimizeMouseClicked
        this.setState(BTampilanGabung.ICONIFIED);
    }//GEN-LAST:event_LabelMinimizeMouseClicked

    private void LabelMinimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelMinimizeMouseEntered
        Border label_border = BorderFactory.createMatteBorder(1, 3, 1, 3, Color.yellow);
        LabelMinimize.setBorder(label_border);
        LabelMinimize.setForeground(Color.yellow);
    }//GEN-LAST:event_LabelMinimizeMouseEntered

    private void LabelMinimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelMinimizeMouseExited
        Border label_border = BorderFactory.createMatteBorder(1, 3, 1, 3,new Color(0,0,153));
        LabelMinimize.setBorder(label_border);
        LabelMinimize.setForeground(new Color(0,0,153));
    }//GEN-LAST:event_LabelMinimizeMouseExited

    private void LabelExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelExitMouseClicked
        this.dispose();
    }//GEN-LAST:event_LabelExitMouseClicked

    private void LabelExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelExitMouseEntered
        Border label_border = BorderFactory.createMatteBorder(1, 3, 1, 3, Color.yellow);
        LabelExit.setBorder(label_border);
        LabelExit.setForeground(Color.yellow);
    }//GEN-LAST:event_LabelExitMouseEntered

    private void LabelExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelExitMouseExited
        Border label_border = BorderFactory.createMatteBorder(1, 3, 1, 3,new Color(0,0,153));
        LabelExit.setBorder(label_border);
        LabelExit.setForeground(new Color(0,0,153));
    }//GEN-LAST:event_LabelExitMouseExited

    private void DisiniMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DisiniMouseEntered
        Border label_border = BorderFactory.createMatteBorder(0, 0, 1, 0,Color.YELLOW);
        Disini.setBorder(label_border);
        Disini.setForeground(Color.YELLOW);
    }//GEN-LAST:event_DisiniMouseEntered

    private void DisiniMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DisiniMouseExited
        Border label_regist = BorderFactory.createMatteBorder(0, 0, 1, 0,Color.WHITE);
        Disini.setBorder(label_regist);
        Disini.setForeground(Color.WHITE);
    }//GEN-LAST:event_DisiniMouseExited

    private void DisiniMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DisiniMouseClicked
        ATampilanDaftarAkun da = new ATampilanDaftarAkun();
        da.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_DisiniMouseClicked

    private void LabelJudulMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelJudulMouseEntered
        LabelJudul.setForeground(Color.YELLOW);
    }//GEN-LAST:event_LabelJudulMouseEntered

    private void LabelJudulMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelJudulMouseExited
        LabelJudul.setForeground(new Color(0,0,153));
    }//GEN-LAST:event_LabelJudulMouseExited

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Disini;
    private javax.swing.JLabel Label1;
    private javax.swing.JLabel Label2;
    private javax.swing.JLabel LabelExit;
    private javax.swing.JLabel LabelJudul;
    private javax.swing.JLabel LabelMinimize;
    private javax.swing.JLabel Note1;
    private javax.swing.JPanel Panel1;
    private javax.swing.JPanel Panel2;
    private javax.swing.JPanel Panel3;
    private javax.swing.JTextField Tnamapengguna;
    private javax.swing.JButton TombolMasuk;
    private javax.swing.JPasswordField Tsandimasuk;
    // End of variables declaration//GEN-END:variables
}