/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MJL.tampilan;

import MJL.data.Admin;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

/**
 *
 * @author WHOAMI
 */
public class CTampilanAdmin extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public CTampilanAdmin() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        Border label_border = BorderFactory.createMatteBorder(1, 3, 1, 3,new Color(0,0,153));
        LabelMinimize.setBorder(label_border);
        LabelExit.setBorder(label_border);
        
        Border field_border = BorderFactory.createMatteBorder(1, 5, 1, 5,new Color(0,0,153));
        Tkodeperusahaan.setBorder(field_border);
        TnamaPerusahaan.setBorder(field_border);
        Tdeskripsi1.setBorder(field_border);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel1 = new javax.swing.JPanel();
        Panel2 = new javax.swing.JPanel(){
            public void paintComponent(Graphics g){
                ImageIcon img = new ImageIcon("src/main/java/MJL/gambar/Gambar8.jpg");
                Image i = img.getImage();
                g.drawImage(i, 0, 0, this);
            }
        }
        ;
        Panel3 = new javax.swing.JPanel();
        LabelJudul = new javax.swing.JLabel();
        LabelMinimize = new javax.swing.JLabel();
        LabelExit = new javax.swing.JLabel();
        Label1 = new javax.swing.JLabel();
        Label4 = new javax.swing.JLabel();
        Label2 = new javax.swing.JLabel();
        Label5 = new javax.swing.JLabel();
        Tkodeperusahaan = new javax.swing.JTextField();
        Label6 = new javax.swing.JLabel();
        Label3 = new javax.swing.JLabel();
        TnamaPerusahaan = new javax.swing.JTextField();
        TombolSimpan = new javax.swing.JButton();
        TombolBersihkan = new javax.swing.JButton();
        TombolKeluar = new javax.swing.JButton();
        TombolPendaftar = new javax.swing.JButton();
        Pilihan = new javax.swing.JComboBox<>();
        Label7 = new javax.swing.JLabel();
        Label8 = new javax.swing.JLabel();
        Tdeskripsi1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        Panel1.setBackground(new java.awt.Color(0, 0, 153));

        Panel2.setBackground(new java.awt.Color(204, 204, 204));
        Panel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panel3.setBackground(new java.awt.Color(0, 0, 153));

        javax.swing.GroupLayout Panel3Layout = new javax.swing.GroupLayout(Panel3);
        Panel3.setLayout(Panel3Layout);
        Panel3Layout.setHorizontalGroup(
            Panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        Panel3Layout.setVerticalGroup(
            Panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        Panel2.add(Panel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, 219));

        LabelJudul.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        LabelJudul.setForeground(new java.awt.Color(0, 0, 153));
        LabelJudul.setText("ADMIN PERUSAHAAN");
        LabelJudul.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LabelJudulMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LabelJudulMouseExited(evt);
            }
        });
        Panel2.add(LabelJudul, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 1, -1, 29));

        LabelMinimize.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        LabelMinimize.setForeground(new java.awt.Color(0, 0, 153));
        LabelMinimize.setText(" -");
        LabelMinimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LabelMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelMinimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LabelMinimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LabelMinimizeMouseExited(evt);
            }
        });
        Panel2.add(LabelMinimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 6, 27, 25));

        LabelExit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        LabelExit.setForeground(new java.awt.Color(0, 0, 153));
        LabelExit.setText(" X");
        LabelExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LabelExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LabelExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LabelExitMouseExited(evt);
            }
        });
        Panel2.add(LabelExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(479, 6, 28, 25));

        Label1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Label1.setText("Status");
        Panel2.add(Label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, -1, -1));

        Label4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Label4.setText(":");
        Panel2.add(Label4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, -1, -1));

        Label2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Label2.setText("Kode Perusahaan");
        Panel2.add(Label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, -1));

        Label5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Label5.setText(":");
        Panel2.add(Label5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, -1, -1));

        Tkodeperusahaan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TkodeperusahaanKeyTyped(evt);
            }
        });
        Panel2.add(Tkodeperusahaan, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 234, -1));

        Label6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Label6.setText(":");
        Panel2.add(Label6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, -1, -1));

        Label3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Label3.setText("Nama Perusahaan");
        Panel2.add(Label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 122, -1));
        Panel2.add(TnamaPerusahaan, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 234, -1));

        TombolSimpan.setBackground(new java.awt.Color(0, 0, 153));
        TombolSimpan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TombolSimpan.setForeground(new java.awt.Color(255, 255, 255));
        TombolSimpan.setText("SIMPAN");
        TombolSimpan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TombolSimpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TombolSimpanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TombolSimpanMouseExited(evt);
            }
        });
        TombolSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TombolSimpanActionPerformed(evt);
            }
        });
        Panel2.add(TombolSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, -1, -1));

        TombolBersihkan.setBackground(new java.awt.Color(0, 0, 153));
        TombolBersihkan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TombolBersihkan.setForeground(new java.awt.Color(255, 255, 255));
        TombolBersihkan.setText("BERSIHKAN");
        TombolBersihkan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TombolBersihkan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TombolBersihkanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TombolBersihkanMouseExited(evt);
            }
        });
        TombolBersihkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TombolBersihkanActionPerformed(evt);
            }
        });
        Panel2.add(TombolBersihkan, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, -1, -1));

        TombolKeluar.setBackground(new java.awt.Color(0, 0, 153));
        TombolKeluar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TombolKeluar.setForeground(new java.awt.Color(255, 255, 255));
        TombolKeluar.setText("KELUAR");
        TombolKeluar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TombolKeluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TombolKeluarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TombolKeluarMouseExited(evt);
            }
        });
        TombolKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TombolKeluarActionPerformed(evt);
            }
        });
        Panel2.add(TombolKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 180, -1, -1));

        TombolPendaftar.setBackground(new java.awt.Color(0, 0, 153));
        TombolPendaftar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TombolPendaftar.setForeground(new java.awt.Color(255, 255, 255));
        TombolPendaftar.setText("PENDAFTAR");
        TombolPendaftar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TombolPendaftar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TombolPendaftarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TombolPendaftarMouseExited(evt);
            }
        });
        TombolPendaftar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TombolPendaftarActionPerformed(evt);
            }
        });
        Panel2.add(TombolPendaftar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, -1, -1));

        Pilihan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih...", "Buka", "Tutup" }));
        Panel2.add(Pilihan, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 125, -1));

        Label7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Label7.setText(":");
        Panel2.add(Label7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, -1, -1));

        Label8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Label8.setText("Deskripsi");
        Panel2.add(Label8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, -1));
        Panel2.add(Tdeskripsi1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 234, -1));

        javax.swing.GroupLayout Panel1Layout = new javax.swing.GroupLayout(Panel1);
        Panel1.setLayout(Panel1Layout);
        Panel1Layout.setHorizontalGroup(
            Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Panel2, javax.swing.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE)
                .addContainerGap())
        );
        Panel1Layout.setVerticalGroup(
            Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Panel2, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LabelMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelMinimizeMouseClicked
        this.setState(CTampilanAdmin.ICONIFIED);
    }//GEN-LAST:event_LabelMinimizeMouseClicked

    private void LabelMinimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelMinimizeMouseEntered
        Border label_border = BorderFactory.createMatteBorder(1, 3, 1, 3, Color.yellow);
        LabelMinimize.setBorder(label_border);
        LabelMinimize.setForeground(Color.yellow);
    }//GEN-LAST:event_LabelMinimizeMouseEntered

    private void LabelMinimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelMinimizeMouseExited
        Border label_border = BorderFactory.createMatteBorder(1, 3, 1, 3,new Color(0,0,153));
        LabelMinimize.setBorder(label_border);
        LabelMinimize.setForeground(new Color(0,0,153));
    }//GEN-LAST:event_LabelMinimizeMouseExited

    private void LabelExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelExitMouseClicked
        this.dispose();
    }//GEN-LAST:event_LabelExitMouseClicked

    private void LabelExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelExitMouseEntered
        Border label_border = BorderFactory.createMatteBorder(1, 3, 1, 3, Color.yellow);
        LabelExit.setBorder(label_border);
        LabelExit.setForeground(Color.yellow);
    }//GEN-LAST:event_LabelExitMouseEntered

    private void LabelExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelExitMouseExited
        Border label_border = BorderFactory.createMatteBorder(1, 3, 1, 3,new Color(0,0,153));
        LabelExit.setBorder(label_border);
        LabelExit.setForeground(new Color(0,0,153));
    }//GEN-LAST:event_LabelExitMouseExited

    private void TombolSimpanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TombolSimpanMouseEntered
        TombolSimpan.setBackground(Color.yellow);
        TombolSimpan.setForeground(Color.black);
    }//GEN-LAST:event_TombolSimpanMouseEntered

    private void TombolSimpanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TombolSimpanMouseExited
        TombolSimpan.setBackground(new Color(0,0,153));
        TombolSimpan.setForeground(Color.white);
    }//GEN-LAST:event_TombolSimpanMouseExited

    private void TombolBersihkanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TombolBersihkanMouseEntered
        TombolBersihkan.setBackground(Color.yellow);
        TombolBersihkan.setForeground(Color.black);
    }//GEN-LAST:event_TombolBersihkanMouseEntered

    private void TombolBersihkanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TombolBersihkanMouseExited
        TombolBersihkan.setBackground(new Color(0,0,153));
        TombolBersihkan.setForeground(Color.white);
    }//GEN-LAST:event_TombolBersihkanMouseExited

    private void TombolBersihkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TombolBersihkanActionPerformed
        Pilihan.setSelectedItem("Pilih...");
        Tkodeperusahaan.setText("");
        TnamaPerusahaan.setText("");
    }//GEN-LAST:event_TombolBersihkanActionPerformed

    private void TombolKeluarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TombolKeluarMouseEntered
        TombolKeluar.setBackground(Color.yellow);
        TombolKeluar.setForeground(Color.black);
    }//GEN-LAST:event_TombolKeluarMouseEntered

    private void TombolKeluarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TombolKeluarMouseExited
        TombolKeluar.setBackground(new Color(0,0,153));
        TombolKeluar.setForeground(Color.white);
    }//GEN-LAST:event_TombolKeluarMouseExited

    private void TombolKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TombolKeluarActionPerformed
        int opsi = JOptionPane.showConfirmDialog(null, "Apa kamu yakin", "Perhatian",JOptionPane.ERROR_MESSAGE);
        if(opsi == JOptionPane.YES_OPTION){
            BTampilanGabung tg = new BTampilanGabung();
            tg.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_TombolKeluarActionPerformed

    private void TombolPendaftarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TombolPendaftarMouseEntered
        TombolPendaftar.setBackground(Color.yellow);
        TombolPendaftar.setForeground(Color.black);
    }//GEN-LAST:event_TombolPendaftarMouseEntered

    private void TombolPendaftarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TombolPendaftarMouseExited
        TombolPendaftar.setBackground(new Color(0,0,153));
        TombolPendaftar.setForeground(Color.white);
    }//GEN-LAST:event_TombolPendaftarMouseExited

    private void TombolPendaftarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TombolPendaftarActionPerformed
        DTampilanPendaftarKerja dk = new DTampilanPendaftarKerja();
        dk.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_TombolPendaftarActionPerformed

    private void TkodeperusahaanKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TkodeperusahaanKeyTyped
        if(Character.isLetter(evt.getKeyChar())){
            evt.consume();
            JOptionPane.showMessageDialog(null, "Harus dalam format angka","Perhatian",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_TkodeperusahaanKeyTyped

    private void LabelJudulMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelJudulMouseEntered
        LabelJudul.setForeground(Color.YELLOW);
    }//GEN-LAST:event_LabelJudulMouseEntered

    private void LabelJudulMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelJudulMouseExited
        LabelJudul.setForeground(new Color(0,0,153));
    }//GEN-LAST:event_LabelJudulMouseExited

    private void TombolSimpanActionPerformed(java.awt.event.ActionEvent evt) {
        String status = (String) Pilihan.getSelectedItem();
        String codeString = Tkodeperusahaan.getText();
        String desc = Tdeskripsi1.getText();
        String nama_perusahaan = TnamaPerusahaan.getText();
        admin.input_data(nama_perusahaan, status, codeString, desc);
    }
    Admin admin = new Admin();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Label1;
    private javax.swing.JLabel Label2;
    private javax.swing.JLabel Label3;
    private javax.swing.JLabel Label4;
    private javax.swing.JLabel Label5;
    private javax.swing.JLabel Label6;
    private javax.swing.JLabel Label7;
    private javax.swing.JLabel Label8;
    private javax.swing.JLabel LabelExit;
    private javax.swing.JLabel LabelJudul;
    private javax.swing.JLabel LabelMinimize;
    private javax.swing.JPanel Panel1;
    private javax.swing.JPanel Panel2;
    private javax.swing.JPanel Panel3;
    private javax.swing.JComboBox<String> Pilihan;
    private javax.swing.JTextField Tdeskripsi1;
    private javax.swing.JTextField Tkodeperusahaan;
    private javax.swing.JTextField TnamaPerusahaan;
    private javax.swing.JButton TombolBersihkan;
    private javax.swing.JButton TombolKeluar;
    private javax.swing.JButton TombolPendaftar;
    private javax.swing.JButton TombolSimpan;
    // End of variables declaration//GEN-END:variables
}