/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MJL.tampilan;

import MJL.data.Pendaftaran;
import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author WHOAMI
 */
public class DTampilanPendaftarKerja extends javax.swing.JFrame {

    /**
     * Creates new form DataWork
     */
    public DTampilanPendaftarKerja() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        
        Border label_border = BorderFactory.createMatteBorder(1, 3, 1, 3,new Color(0,0,153));
        LabelMinimize.setBorder(label_border);
        LabelExit.setBorder(label_border);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel1 = new javax.swing.JPanel();
        Panel2 = new javax.swing.JPanel();
        Panel3 = new javax.swing.JPanel();
        LabelJudul = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tabel = new javax.swing.JTable();
        LabelMinimize = new javax.swing.JLabel();
        LabelExit = new javax.swing.JLabel();
        TombolSegarkan = new javax.swing.JButton();
        TombolEditData = new javax.swing.JButton();
        Panel4 = new javax.swing.JPanel();
        TombolKembali = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        Panel1.setBackground(new java.awt.Color(0, 0, 153));

        Panel2.setBackground(new java.awt.Color(255, 255, 255));
        Panel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panel3.setBackground(new java.awt.Color(0, 0, 153));

        javax.swing.GroupLayout Panel3Layout = new javax.swing.GroupLayout(Panel3);
        Panel3.setLayout(Panel3Layout);
        Panel3Layout.setHorizontalGroup(
            Panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        Panel3Layout.setVerticalGroup(
            Panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        Panel2.add(Panel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, 659));

        LabelJudul.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        LabelJudul.setForeground(new java.awt.Color(0, 0, 153));
        LabelJudul.setText("DAFTAR PENDAFTAR KERJA");
        LabelJudul.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LabelJudulMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LabelJudulMouseExited(evt);
            }
        });
        Panel2.add(LabelJudul, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 1, -1, 29));

        Tabel.setModel(new javax.swing.table.DefaultTableModel(
            pendaftaran.get_data_pendaftaran(),
            new String [] {
                "nomor", "nama", "tempatLahir", "tanggalLahir", "kelamin", "alamat", "agama", "statusPernikahan",
                    "pengalaman", "lulusan", "telepon", "namaPerusahaan", "foto", "status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false,false, false, false, false,false, false, false, false,false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });

        Tabel.setCellSelectionEnabled(true);
        jScrollPane2.setViewportView(Tabel);
        Tabel.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        if (Tabel.getColumnModel().getColumnCount() > 0) {
            Tabel.getColumnModel().getColumn(0).setResizable(false);
            Tabel.getColumnModel().getColumn(1).setResizable(false);
            Tabel.getColumnModel().getColumn(2).setResizable(false);
            Tabel.getColumnModel().getColumn(3).setResizable(false);
        }

        Panel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 37, 1262, 600));

        LabelMinimize.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        LabelMinimize.setForeground(new java.awt.Color(0, 0, 153));
        LabelMinimize.setText(" -");
        LabelMinimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LabelMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelMinimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LabelMinimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LabelMinimizeMouseExited(evt);
            }
        });
        Panel2.add(LabelMinimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(1234, 6, 25, 25));

        LabelExit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        LabelExit.setForeground(new java.awt.Color(0, 0, 153));
        LabelExit.setText(" X");
        LabelExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LabelExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LabelExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LabelExitMouseExited(evt);
            }
        });
        Panel2.add(LabelExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1265, 6, 29, 25));

        TombolSegarkan.setBackground(new java.awt.Color(0, 0, 153));
        TombolSegarkan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TombolSegarkan.setForeground(new java.awt.Color(255, 255, 255));
        TombolSegarkan.setText("SEGARKAN");
        TombolSegarkan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TombolSegarkan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TombolSegarkanMouseClicked(evt);
                close();
                new DTampilanPendaftarKerja().setVisible(true);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TombolSegarkanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TombolSegarkanMouseExited(evt);
            }
        });
        Panel2.add(TombolSegarkan, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 640, -1, -1));

        TombolEditData.setBackground(new java.awt.Color(0, 0, 153));
        TombolEditData.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TombolEditData.setForeground(new java.awt.Color(255, 255, 255));
        TombolEditData.setText("EDIT DATA");
        TombolEditData.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TombolEditData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TombolEditDataMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TombolEditDataMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TombolEditDataMouseExited(evt);
            }
        });
        Panel2.add(TombolEditData, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 640, -1, -1));

        Panel4.setBackground(new java.awt.Color(0, 0, 153));

        javax.swing.GroupLayout Panel4Layout = new javax.swing.GroupLayout(Panel4);
        Panel4.setLayout(Panel4Layout);
        Panel4Layout.setHorizontalGroup(
            Panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        Panel4Layout.setVerticalGroup(
            Panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        Panel2.add(Panel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 6, -1, 659));

        TombolKembali.setBackground(new java.awt.Color(0, 0, 153));
        TombolKembali.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TombolKembali.setForeground(new java.awt.Color(255, 255, 255));
        TombolKembali.setText("KEMBALI");
        TombolKembali.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TombolKembali.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TombolKembaliMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TombolKembaliMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TombolKembaliMouseExited(evt);
            }
        });
        Panel2.add(TombolKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 640, -1, -1));

        javax.swing.GroupLayout Panel1Layout = new javax.swing.GroupLayout(Panel1);
        Panel1.setLayout(Panel1Layout);
        Panel1Layout.setHorizontalGroup(
            Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Panel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1327, Short.MAX_VALUE)
                .addContainerGap())
        );
        Panel1Layout.setVerticalGroup(
            Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Panel2, javax.swing.GroupLayout.DEFAULT_SIZE, 673, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();


    }// </editor-fold>//GEN-END:initComponents

    public void close(){
        this.dispose();
    }

    private void LabelMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelMinimizeMouseClicked
        this.setState(DTampilanPendaftarKerja.ICONIFIED);
    }//GEN-LAST:event_LabelMinimizeMouseClicked

    private void LabelMinimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelMinimizeMouseEntered
        Border label_border = BorderFactory.createMatteBorder(1, 3, 1, 3, Color.yellow);
        LabelMinimize.setBorder(label_border);
        LabelMinimize.setForeground(Color.yellow);
    }//GEN-LAST:event_LabelMinimizeMouseEntered

    private void LabelMinimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelMinimizeMouseExited
        Border label_border = BorderFactory.createMatteBorder(1, 3, 1, 3,new Color(0,0,153));
        LabelMinimize.setBorder(label_border);
        LabelMinimize.setForeground(new Color(0,0,153));
    }//GEN-LAST:event_LabelMinimizeMouseExited

    private void LabelExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelExitMouseClicked
        this.dispose();
    }//GEN-LAST:event_LabelExitMouseClicked

    private void LabelExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelExitMouseEntered
        Border label_border = BorderFactory.createMatteBorder(1, 3, 1, 3, Color.yellow);
        LabelExit.setBorder(label_border);
        LabelExit.setForeground(Color.yellow);
    }//GEN-LAST:event_LabelExitMouseEntered

    private void LabelExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelExitMouseExited
        Border label_border = BorderFactory.createMatteBorder(1, 3, 1, 3,new Color(0,0,153));
        LabelExit.setBorder(label_border);
        LabelExit.setForeground(new Color(0,0,153));
    }//GEN-LAST:event_LabelExitMouseExited

    private void TombolSegarkanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TombolSegarkanMouseClicked
        DefaultTableModel model = (DefaultTableModel)Tabel.getModel();
        //show_data();
    }//GEN-LAST:event_TombolSegarkanMouseClicked

    private void TombolSegarkanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TombolSegarkanMouseEntered
        TombolSegarkan.setBackground(new Color(255,255,51));
        TombolSegarkan.setForeground(Color.black);
    }//GEN-LAST:event_TombolSegarkanMouseEntered

    private void TombolSegarkanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TombolSegarkanMouseExited
        TombolSegarkan.setBackground(new Color(0,0,153));
        TombolSegarkan.setForeground(Color.white);
    }//GEN-LAST:event_TombolSegarkanMouseExited

    private void TombolEditDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TombolEditDataMouseClicked
        ETampilanEdit te = new ETampilanEdit();
        te.setVisible(true);
    }//GEN-LAST:event_TombolEditDataMouseClicked

    private void TombolEditDataMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TombolEditDataMouseEntered
        TombolEditData.setBackground(new Color(255,255,51));
        TombolEditData.setForeground(Color.black);
    }//GEN-LAST:event_TombolEditDataMouseEntered

    private void TombolEditDataMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TombolEditDataMouseExited
        TombolEditData.setBackground(new Color(0,0,153));
        TombolEditData.setForeground(Color.white);
    }//GEN-LAST:event_TombolEditDataMouseExited

    private void TombolKembaliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TombolKembaliMouseClicked
        CTampilanAdmin ta = new CTampilanAdmin();
        ta.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_TombolKembaliMouseClicked

    private void TombolKembaliMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TombolKembaliMouseEntered
        TombolKembali.setBackground(new Color(255,255,51));
        TombolKembali.setForeground(Color.black);
    }//GEN-LAST:event_TombolKembaliMouseEntered

    private void TombolKembaliMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TombolKembaliMouseExited
        TombolKembali.setBackground(new Color(0,0,153));
        TombolKembali.setForeground(Color.white);
    }//GEN-LAST:event_TombolKembaliMouseExited

    private void LabelJudulMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelJudulMouseEntered
        LabelJudul.setForeground(Color.YELLOW);
    }//GEN-LAST:event_LabelJudulMouseEntered

    private void LabelJudulMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelJudulMouseExited
        LabelJudul.setForeground(new Color(0,0,153));
    }//GEN-LAST:event_LabelJudulMouseExited

    // Variables declaration - do not modify//GEN-BEGIN:variables
    Pendaftaran pendaftaran = new Pendaftaran();
    private javax.swing.JLabel LabelExit;
    private javax.swing.JLabel LabelJudul;
    private javax.swing.JLabel LabelMinimize;
    private javax.swing.JPanel Panel1;
    private javax.swing.JPanel Panel2;
    private javax.swing.JPanel Panel3;
    private javax.swing.JPanel Panel4;
    private javax.swing.JTable Tabel;
    private javax.swing.JButton TombolEditData;
    private javax.swing.JButton TombolKembali;
    private javax.swing.JButton TombolSegarkan;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
