/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MJL.tampilan;

import MJL.data.Login;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
/**
 *
 * @author WHOAMI
 */
public class FTampilanMenu extends javax.swing.JFrame {
    /**
     * Creates new form TampilanMenu
     */
    public FTampilanMenu() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        Border tampilan_border = BorderFactory.createMatteBorder(2, 2, 2, 2,new Color(0,0,153));
        Tampilan.setBorder(tampilan_border);
        
        Border label_border = BorderFactory.createMatteBorder(1, 3, 1, 3,new Color(0,0,153));
        LabelMinimize.setBorder(label_border);
        LabelExit.setBorder(label_border);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        Tampilan.setText(Login.login_user);

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel(){
            public void paintComponent(Graphics g){
                ImageIcon img = new ImageIcon("src/main/java/MJL/gambar/Gambar6.jpg");
                Image i = img.getImage();
                g.drawImage(i, 0, 0, this);
            }
        }
        ;
        LogoMJB = new javax.swing.JPanel(){
            public void paintComponent(Graphics g){
                ImageIcon img = new ImageIcon("src/main/java/MJL/gambar/MJL.png");
                Image i = img.getImage();
                g.drawImage(i, 0, 0, this);
            }
        }
        ;
        TombolKeluar = new javax.swing.JButton();
        TombolInfo = new javax.swing.JButton();
        Panel3 = new javax.swing.JPanel();
        LabelJudul = new javax.swing.JLabel();
        TombolDaftarKerja = new javax.swing.JButton();
        TombolStatus = new javax.swing.JButton();
        LabelMinimize = new javax.swing.JLabel();
        LabelExit = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 153));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout LogoMJBLayout = new javax.swing.GroupLayout(LogoMJB);
        LogoMJB.setLayout(LogoMJBLayout);
        LogoMJBLayout.setHorizontalGroup(
            LogoMJBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        LogoMJBLayout.setVerticalGroup(
            LogoMJBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        jPanel2.add(LogoMJB, new org.netbeans.lib.awtextra.AbsoluteConstraints(352, 99, -1, -1));

        TombolKeluar.setBackground(new java.awt.Color(0, 0, 153));
        TombolKeluar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TombolKeluar.setForeground(new java.awt.Color(255, 255, 255));
        TombolKeluar.setText("KELUAR");
        TombolKeluar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TombolKeluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TombolKeluarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TombolKeluarMouseExited(evt);
            }
        });
        TombolKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TombolKeluarActionPerformed(evt);
            }
        });
        jPanel2.add(TombolKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 330, -1, -1));

        TombolInfo.setBackground(new java.awt.Color(0, 0, 153));
        TombolInfo.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        TombolInfo.setForeground(new java.awt.Color(255, 255, 255));
        TombolInfo.setText("INFORMASI LOWONGAN KERJA");
        TombolInfo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TombolInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TombolInfoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TombolInfoMouseExited(evt);
            }
        });
        TombolInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TombolInfoActionPerformed(evt);
            }
        });
        jPanel2.add(TombolInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 99, 240, 50));

        Panel3.setBackground(new java.awt.Color(0, 0, 153));

        javax.swing.GroupLayout Panel3Layout = new javax.swing.GroupLayout(Panel3);
        Panel3.setLayout(Panel3Layout);
        Panel3Layout.setHorizontalGroup(
            Panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        Panel3Layout.setVerticalGroup(
            Panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel2.add(Panel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, 357));

        LabelJudul.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        LabelJudul.setForeground(new java.awt.Color(0, 0, 153));
        LabelJudul.setText("MENU AWAL");
        LabelJudul.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LabelJudulMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LabelJudulMouseExited(evt);
            }
        });
        jPanel2.add(LabelJudul, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, -1, 28));

        TombolDaftarKerja.setBackground(new java.awt.Color(0, 0, 153));
        TombolDaftarKerja.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        TombolDaftarKerja.setForeground(new java.awt.Color(255, 255, 255));
        TombolDaftarKerja.setText("PENDAFTARAN KERJA");
        TombolDaftarKerja.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TombolDaftarKerja.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TombolDaftarKerjaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TombolDaftarKerjaMouseExited(evt);
            }
        });
        TombolDaftarKerja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TombolDaftarKerjaActionPerformed(evt);
            }
        });
        jPanel2.add(TombolDaftarKerja, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 174, 240, 50));

        TombolStatus.setBackground(new java.awt.Color(0, 0, 153));
        TombolStatus.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        TombolStatus.setForeground(new java.awt.Color(255, 255, 255));
        TombolStatus.setText("STATUS");
        TombolStatus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TombolStatus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TombolStatusMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TombolStatusMouseExited(evt);
            }
        });
        TombolStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TombolStatusActionPerformed(evt);
            }
        });
        jPanel2.add(TombolStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 249, 240, 50));

        LabelMinimize.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        LabelMinimize.setForeground(new java.awt.Color(0, 0, 153));
        LabelMinimize.setText(" -");
        LabelMinimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LabelMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelMinimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LabelMinimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LabelMinimizeMouseExited(evt);
            }
        });
        jPanel2.add(LabelMinimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 5, 25, 25));

        LabelExit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        LabelExit.setForeground(new java.awt.Color(0, 0, 153));
        LabelExit.setText(" X");
        LabelExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LabelExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LabelExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LabelExitMouseExited(evt);
            }
        });
        jPanel2.add(LabelExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 5, 29, 25));

        Tampilan.setBackground(new java.awt.Color(255, 255, 255));
        Tampilan.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        Tampilan.setForeground(new java.awt.Color(255, 255, 255));
        Tampilan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Tampilan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TampilanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TampilanMouseExited(evt);
            }
        });
        jPanel2.add(Tampilan, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 40, 90, 22));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Masuk di :");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 40, -1, 22));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 592, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();

        TombolDaftarKerja.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                new HTampilanDaftarKerja().setVisible(true);
                back();
            }
        });

        TombolInfo.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                new GTampilanInformasi().setVisible(true);
                back();
            }
        });

        TombolStatus.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                new ITampilanStatus().setVisible(true);
                back();
            }
        });
    }// </editor-fold>//GEN-END:initComponents

    private void back(){
        this.dispose();
    }

    private void LabelMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelMinimizeMouseClicked
        this.setState(FTampilanMenu.ICONIFIED);
    }//GEN-LAST:event_LabelMinimizeMouseClicked

    private void LabelMinimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelMinimizeMouseEntered
        Border label_border = BorderFactory.createMatteBorder(1, 3, 1, 3, Color.yellow);
        LabelMinimize.setBorder(label_border);
        LabelMinimize.setForeground(Color.yellow);
    }//GEN-LAST:event_LabelMinimizeMouseEntered

    private void LabelMinimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelMinimizeMouseExited
        Border label_border = BorderFactory.createMatteBorder(1, 3, 1, 3,new Color(0,0,153));
        LabelMinimize.setBorder(label_border);
        LabelMinimize.setForeground(new Color(0,0,153));
    }//GEN-LAST:event_LabelMinimizeMouseExited

    private void LabelExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelExitMouseClicked
        this.dispose();
    }//GEN-LAST:event_LabelExitMouseClicked

    private void LabelExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelExitMouseEntered
        Border label_border = BorderFactory.createMatteBorder(1, 3, 1, 3, Color.yellow);
        LabelExit.setBorder(label_border);
        LabelExit.setForeground(Color.yellow);
    }//GEN-LAST:event_LabelExitMouseEntered

    private void LabelExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelExitMouseExited
        Border label_border = BorderFactory.createMatteBorder(1, 3, 1, 3,new Color(0,0,153));
        LabelExit.setBorder(label_border);
        LabelExit.setForeground(new Color(0,0,153));
    }//GEN-LAST:event_LabelExitMouseExited

    private void TombolInfoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TombolInfoMouseEntered
        TombolInfo.setBackground(new Color(255,255,51));
        TombolInfo.setForeground(Color.black);
    }//GEN-LAST:event_TombolInfoMouseEntered

    private void TombolInfoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TombolInfoMouseExited
        TombolInfo.setBackground(new Color(0,0,153));
        TombolInfo.setForeground(Color.white);
    }//GEN-LAST:event_TombolInfoMouseExited

    private void TombolDaftarKerjaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TombolDaftarKerjaMouseEntered
        TombolDaftarKerja.setBackground(new Color(255,255,51));
        TombolDaftarKerja.setForeground(Color.black);
    }//GEN-LAST:event_TombolDaftarKerjaMouseEntered

    private void TombolDaftarKerjaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TombolDaftarKerjaMouseExited
        TombolDaftarKerja.setBackground(new Color(0,0,153));
        TombolDaftarKerja.setForeground(Color.white);
    }//GEN-LAST:event_TombolDaftarKerjaMouseExited

    private void TombolStatusMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TombolStatusMouseEntered
        TombolStatus.setBackground(new Color(255,255,51));
        TombolStatus.setForeground(Color.black);
    }//GEN-LAST:event_TombolStatusMouseEntered

    private void TombolStatusMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TombolStatusMouseExited
        TombolStatus.setBackground(new Color(0,0,153));
        TombolStatus.setForeground(Color.white);
    }//GEN-LAST:event_TombolStatusMouseExited

    private void TombolInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TombolInfoActionPerformed
        
    }//GEN-LAST:event_TombolInfoActionPerformed

    private void TombolDaftarKerjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TombolDaftarKerjaActionPerformed
        
    }//GEN-LAST:event_TombolDaftarKerjaActionPerformed

    private void TombolStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TombolStatusActionPerformed
        
    }//GEN-LAST:event_TombolStatusActionPerformed

    private void TombolKeluarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TombolKeluarMouseEntered
        TombolKeluar.setBackground(new Color(255,255,51));
        TombolKeluar.setForeground(Color.black);
    }//GEN-LAST:event_TombolKeluarMouseEntered

    private void TombolKeluarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TombolKeluarMouseExited
        TombolKeluar.setBackground(new Color(0,0,153));
        TombolKeluar.setForeground(Color.white);
    }//GEN-LAST:event_TombolKeluarMouseExited

    private void TombolKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TombolKeluarActionPerformed
        int opsi = JOptionPane.showConfirmDialog(null, "Apa kamu yakin ?", "Perhatian",JOptionPane.ERROR_MESSAGE);
        if(opsi == JOptionPane.YES_OPTION){
            BTampilanGabung tg = new BTampilanGabung();
            tg.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_TombolKeluarActionPerformed

    private void LabelJudulMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelJudulMouseEntered
        LabelJudul.setForeground(Color.YELLOW);
    }//GEN-LAST:event_LabelJudulMouseEntered

    private void LabelJudulMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelJudulMouseExited
        LabelJudul.setForeground(new Color(0,0,153));
    }//GEN-LAST:event_LabelJudulMouseExited

    private void TampilanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TampilanMouseEntered
        Border tampilan_border = BorderFactory.createMatteBorder(2, 2, 2, 2,Color.WHITE);
        Tampilan.setBorder(tampilan_border);
    }//GEN-LAST:event_TampilanMouseEntered

    private void TampilanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TampilanMouseExited
        Border tampilan_border = BorderFactory.createMatteBorder(2, 2, 2, 2,new Color(0,0,153));
        Tampilan.setBorder(tampilan_border);
    }//GEN-LAST:event_TampilanMouseExited

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelExit;
    private javax.swing.JLabel LabelJudul;
    private javax.swing.JLabel LabelMinimize;
    private javax.swing.JPanel LogoMJB;
    private javax.swing.JPanel Panel3;
    public javax.swing.JLabel Tampilan = new javax.swing.JLabel();
    private javax.swing.JButton TombolDaftarKerja;
    private javax.swing.JButton TombolInfo;
    private javax.swing.JButton TombolKeluar;
    private javax.swing.JButton TombolStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}