package MJL.tampilan;

import MJL.data.DaftarAkun;
import MJL.data.Login;
import MJL.data.Pendaftaran;
import MJL.data.Perusahaan;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.io.File;
import javax.swing.BorderFactory;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author acerb
 */
public class HTampilanDaftarKerja extends javax.swing.JFrame {
    String selectedimg = "";
    /**
     * Creates new form
     */
    public HTampilanDaftarKerja() {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            System.out.println(ex);
        }

        initComponents();
        this.setLocationRelativeTo(null);

        
        ButtonGroup bg = new ButtonGroup();
        bg.add(Rpria);
        bg.add(Rwanita);
        
        Border label_border = BorderFactory.createMatteBorder(1, 3, 1, 3,new Color(0,0,153));
        LabelMinimize.setBorder(label_border);
        LabelExit.setBorder(label_border);
        
        Border img_border = BorderFactory.createMatteBorder(2, 2, 2, 2,new Color(0,0,153));
        LabelFoto.setBorder(img_border);
        
        Border field_border = BorderFactory.createMatteBorder(1, 5, 1, 5,new Color(0,0,153));
        Tnama.setBorder(field_border);
        Ttempatlahir.setBorder(field_border);
        Dtanggallahir.setBorder(field_border);
        Talamat.setBorder(field_border);
        Tpengalaman.setBorder(field_border);
        Ttelepon.setBorder(field_border);
        Tfoto.setBorder(field_border);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel(){
            public void paintComponent(Graphics g){
                ImageIcon img = new ImageIcon("src/main/java/MJL/gambar/Gambar4.jpg");
                Image i = img.getImage();
                g.drawImage(i, 0, 0, this);
            }
        }
        ;
        Label15 = new javax.swing.JLabel();
        Tnama = new javax.swing.JTextField();
        Label16 = new javax.swing.JLabel();
        Ttempatlahir = new javax.swing.JTextField();
        Label17 = new javax.swing.JLabel();
        Dtanggallahir = new com.toedter.calendar.JDateChooser();
        Label18 = new javax.swing.JLabel();
        Label19 = new javax.swing.JLabel();
        Talamat = new javax.swing.JTextField();
        Label20 = new javax.swing.JLabel();
        Pagama = new javax.swing.JComboBox<>();
        Label21 = new javax.swing.JLabel();
        Ppernikahan = new javax.swing.JComboBox<>();
        Label22 = new javax.swing.JLabel();
        Tpengalaman = new javax.swing.JTextField();
        Label23 = new javax.swing.JLabel();
        Plulusan = new javax.swing.JComboBox<>();
        Label24 = new javax.swing.JLabel();
        Ttelepon = new javax.swing.JTextField();
        Label25 = new javax.swing.JLabel();
        Label26 = new javax.swing.JLabel();
        TombolTelusuri = new javax.swing.JButton();
        TombolKembali = new javax.swing.JButton();
        TombolSimpan = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        LabelJudul = new javax.swing.JLabel();
        LabelMinimize = new javax.swing.JLabel();
        LabelExit = new javax.swing.JLabel();
        Label2 = new javax.swing.JLabel();
        Label3 = new javax.swing.JLabel();
        Label4 = new javax.swing.JLabel();
        Label5 = new javax.swing.JLabel();
        Label6 = new javax.swing.JLabel();
        Label7 = new javax.swing.JLabel();
        Label8 = new javax.swing.JLabel();
        Label9 = new javax.swing.JLabel();
        Label10 = new javax.swing.JLabel();
        Label11 = new javax.swing.JLabel();
        Label12 = new javax.swing.JLabel();
        label13 = new javax.swing.JLabel();
        Rpria = new javax.swing.JRadioButton();
        Rwanita = new javax.swing.JRadioButton();
        LabelFoto = new javax.swing.JLabel();
        Tfoto = new javax.swing.JTextField();
        Pperusahaan = new javax.swing.JComboBox<>();
        LabelNote2 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(580, 615));

        jPanel1.setBackground(new java.awt.Color(0, 0, 153));
        jPanel1.setPreferredSize(new java.awt.Dimension(560, 605));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setPreferredSize(new java.awt.Dimension(557, 588));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Label15.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        Label15.setText("Nama");
        jPanel2.add(Label15, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 62, -1, -1));

        Tnama.setPreferredSize(new java.awt.Dimension(128, 22));
        Tnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TnamaActionPerformed(evt);
            }
        });
        jPanel2.add(Tnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 212, -1));

        Label16.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        Label16.setText("Tempat Lahir");
        jPanel2.add(Label16, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 92, -1, -1));

        Ttempatlahir.setPreferredSize(new java.awt.Dimension(128, 22));
        Ttempatlahir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TtempatlahirActionPerformed(evt);
            }
        });
        jPanel2.add(Ttempatlahir, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 212, -1));

        Label17.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        Label17.setText("Tanggal Lahir");
        jPanel2.add(Label17, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 122, -1, -1));

        Dtanggallahir.setDateFormatString("yyyy-MM-dd");
        Dtanggallahir.setPreferredSize(new java.awt.Dimension(118, 22));
        jPanel2.add(Dtanggallahir, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 212, 28));

        Label18.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        Label18.setText("Jenis Kelamin");
        jPanel2.add(Label18, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 153, -1, -1));

        Label19.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        Label19.setText("Alamat");
        jPanel2.add(Label19, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 182, -1, -1));

        Talamat.setPreferredSize(new java.awt.Dimension(128, 22));
        jPanel2.add(Talamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 212, -1));

        Label20.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        Label20.setText("Agama");
        jPanel2.add(Label20, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 212, -1, -1));

        Pagama.setMaximumRowCount(5);
        Pagama.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih...", "Islam", "Kristen", "Katolik", "Hindu", "Budha", "Konghucu" }));
        Pagama.setPreferredSize(new java.awt.Dimension(100, 22));
        jPanel2.add(Pagama, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 212, -1));

        Label21.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        Label21.setText("Status Pernikahan");
        jPanel2.add(Label21, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 242, -1, -1));

        Ppernikahan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih...", "Menikah", "Belum menikah" }));
        Ppernikahan.setPreferredSize(new java.awt.Dimension(100, 22));
        Ppernikahan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PpernikahanActionPerformed(evt);
            }
        });
        jPanel2.add(Ppernikahan, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 212, -1));

        Label22.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        Label22.setText("Pengalaman");
        jPanel2.add(Label22, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 272, -1, -1));

        Tpengalaman.setPreferredSize(new java.awt.Dimension(128, 22));
        Tpengalaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TpengalamanActionPerformed(evt);
            }
        });
        jPanel2.add(Tpengalaman, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 212, -1));

        Label23.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        Label23.setText("Lulusan Terakhir");
        jPanel2.add(Label23, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 302, 111, -1));

        Plulusan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih...", "SMA", "SMK", "Sarjana" }));
        Plulusan.setPreferredSize(new java.awt.Dimension(100, 22));
        jPanel2.add(Plulusan, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, 212, -1));

        Label24.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        Label24.setText("Telepon");
        jPanel2.add(Label24, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 332, -1, -1));

        Ttelepon.setPreferredSize(new java.awt.Dimension(128, 22));
        Ttelepon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TteleponActionPerformed(evt);
            }
        });
        Ttelepon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TteleponKeyTyped(evt);
            }
        });
        jPanel2.add(Ttelepon, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, 212, -1));

        Label25.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        Label25.setText("Nama Perusahaan");
        jPanel2.add(Label25, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 362, -1, -1));

        Label26.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        Label26.setText("Foto");
        jPanel2.add(Label26, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 392, -1, -1));

        TombolTelusuri.setBackground(new java.awt.Color(0, 0, 153));
        TombolTelusuri.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TombolTelusuri.setForeground(new java.awt.Color(255, 255, 255));
        TombolTelusuri.setText("TELUSURI");
        TombolTelusuri.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TombolTelusuri.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TombolTelusuriMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TombolTelusuriMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TombolTelusuriMouseExited(evt);
            }
        });
        TombolTelusuri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TombolTelusuriActionPerformed(evt);
            }
        });
        jPanel2.add(TombolTelusuri, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 390, -1, -1));

        TombolKembali.setBackground(new java.awt.Color(0, 0, 153));
        TombolKembali.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TombolKembali.setForeground(new java.awt.Color(255, 255, 255));
        TombolKembali.setText("KEMBALI");
        TombolKembali.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TombolKembali.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TombolKembaliMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TombolKembaliMouseExited(evt);
            }
        });
        TombolKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TombolKembaliActionPerformed(evt);
            }
        });
        jPanel2.add(TombolKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 470, 86, -1));

        TombolSimpan.setBackground(new java.awt.Color(0, 0, 153));
        TombolSimpan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TombolSimpan.setForeground(new java.awt.Color(255, 255, 255));
        TombolSimpan.setText("SIMPAN");
        TombolSimpan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TombolSimpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TombolSimpanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TombolSimpanMouseExited(evt);
            }
        });
        TombolSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TombolSimpanActionPerformed(evt);
            }
        });
        jPanel2.add(TombolSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 430, 86, -1));

        jPanel3.setBackground(new java.awt.Color(0, 0, 153));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 577, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        LabelJudul.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        LabelJudul.setForeground(new java.awt.Color(0, 0, 153));
        LabelJudul.setText("DAFTAR KERJA");
        LabelJudul.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LabelJudulMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LabelJudulMouseExited(evt);
            }
        });
        jPanel2.add(LabelJudul, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, -1, 29));

        LabelMinimize.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        LabelMinimize.setForeground(new java.awt.Color(0, 0, 153));
        LabelMinimize.setText(" -");
        LabelMinimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LabelMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelMinimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LabelMinimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LabelMinimizeMouseExited(evt);
            }
        });
        jPanel2.add(LabelMinimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(404, 6, 25, 25));

        LabelExit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        LabelExit.setForeground(new java.awt.Color(0, 0, 153));
        LabelExit.setText(" X");
        LabelExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LabelExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LabelExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LabelExitMouseExited(evt);
            }
        });
        jPanel2.add(LabelExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 6, 29, 25));

        Label2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Label2.setText(":");
        jPanel2.add(Label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 6, -1));

        Label3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Label3.setText(":");
        jPanel2.add(Label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 6, -1));

        Label4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Label4.setText(":");
        jPanel2.add(Label4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 6, -1));

        Label5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Label5.setText(":");
        jPanel2.add(Label5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 6, -1));

        Label6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Label6.setText(":");
        jPanel2.add(Label6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 6, -1));

        Label7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Label7.setText(":");
        jPanel2.add(Label7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 6, -1));

        Label8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Label8.setText(":");
        jPanel2.add(Label8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 6, -1));

        Label9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Label9.setText(":");
        jPanel2.add(Label9, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 6, -1));

        Label10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Label10.setText(":");
        jPanel2.add(Label10, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, 6, -1));

        Label11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Label11.setText(":");
        jPanel2.add(Label11, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, 6, -1));

        Label12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Label12.setText(":");
        jPanel2.add(Label12, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 360, 6, -1));

        label13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        label13.setText(":");
        jPanel2.add(label13, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 390, 6, -1));

        Rpria.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Rpria.setText("Pria");
        Rpria.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(Rpria, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 56, -1));

        Rwanita.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Rwanita.setText("Wanita");
        Rwanita.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(Rwanita, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, -1, -1));

        LabelFoto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LabelFoto.setText("       Pratinjau");
        jPanel2.add(LabelFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 390, 120, 134));
        jPanel2.add(Tfoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 530, 120, -1));

        Pperusahaan.setMaximumRowCount(3);
        Pperusahaan.setModel(new javax.swing.DefaultComboBoxModel<>(perusahaan.get_perusahaan_buka()));
        jPanel2.add(Pperusahaan, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 360, 212, -1));

        LabelNote2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LabelNote2.setText("Lokasi:");
        jPanel2.add(LabelNote2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 530, -1, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 606, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TnamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TnamaActionPerformed

    private void TtempatlahirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TtempatlahirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TtempatlahirActionPerformed

    private void PpernikahanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PpernikahanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PpernikahanActionPerformed

    private void TteleponActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TteleponActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TteleponActionPerformed

    private void TombolTelusuriMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TombolTelusuriMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_TombolTelusuriMouseClicked

    private void TombolTelusuriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TombolTelusuriActionPerformed
        JFileChooser browseImageFile = new JFileChooser();
        FileNameExtensionFilter fnef = new FileNameExtensionFilter("IMAGES", "png", "jpg", "jpeg");
        browseImageFile.addChoosableFileFilter(fnef);
        int showOpenDialogue = browseImageFile.showOpenDialog(null);
 
        if (showOpenDialogue == JFileChooser.APPROVE_OPTION) {
            File selectedImageFile = browseImageFile.getSelectedFile();
            selectedimg = selectedImageFile.getAbsolutePath();
            Tfoto.setText(selectedimg);
            ImageIcon img = new ImageIcon(selectedimg);
            Image image = img.getImage().getScaledInstance(LabelFoto.getWidth(), LabelFoto.getHeight(), Image.SCALE_SMOOTH);
            LabelFoto.setIcon(new ImageIcon(image));
        }
        
    }//GEN-LAST:event_TombolTelusuriActionPerformed

    private void TpengalamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TpengalamanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TpengalamanActionPerformed

    private void TombolKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TombolKembaliActionPerformed
        FTampilanMenu tm = new FTampilanMenu();
        tm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_TombolKembaliActionPerformed

    private void TombolSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TombolSimpanActionPerformed
        String[] data_regis = new String[12];
        String username = Login.login_user;
        data_regis[0] = Tnama.getText();
        data_regis[1] = Ttempatlahir.getText();
        data_regis[2] = String.valueOf(Dtanggallahir.getDate());
        if (Rpria.isSelected()){
            data_regis[3] = "Laki-laki";
        } else if (Rwanita.isSelected()) {
            data_regis[3] = "Wanita";
        }
        data_regis[4] = Talamat.getText();
        data_regis[5] = (String) Pagama.getSelectedItem();
        data_regis[6] = (String) Ppernikahan.getSelectedItem();
        data_regis[7] = Tpengalaman.getText();
        data_regis[8] = (String) Plulusan.getSelectedItem();
        data_regis[9] = Ttelepon.getText();
        data_regis[10] = (String) Pperusahaan.getSelectedItem();
        data_regis[11] = Tfoto.getText();
        pendaftaran.daftar_kerja(username, data_regis);
    }//GEN-LAST:event_TombolSimpanActionPerformed
    
    private void LabelMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelMinimizeMouseClicked
        this.setState(HTampilanDaftarKerja.ICONIFIED);
    }//GEN-LAST:event_LabelMinimizeMouseClicked

    private void LabelMinimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelMinimizeMouseEntered
        Border label_border = BorderFactory.createMatteBorder(1, 3, 1, 3, Color.yellow);
        LabelMinimize.setBorder(label_border);
        LabelMinimize.setForeground(Color.yellow);
    }//GEN-LAST:event_LabelMinimizeMouseEntered

    private void LabelMinimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelMinimizeMouseExited
        Border label_border = BorderFactory.createMatteBorder(1, 3, 1, 3,new Color(0,0,153));
        LabelMinimize.setBorder(label_border);
        LabelMinimize.setForeground(new Color(0,0,153));
    }//GEN-LAST:event_LabelMinimizeMouseExited

    private void LabelExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelExitMouseClicked
        this.dispose();
    }//GEN-LAST:event_LabelExitMouseClicked
    private void LabelExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelExitMouseEntered
        Border label_border = BorderFactory.createMatteBorder(1, 3, 1, 3, Color.yellow);
        LabelExit.setBorder(label_border);
        LabelExit.setForeground(Color.yellow);
    }//GEN-LAST:event_LabelExitMouseEntered

    private void LabelExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelExitMouseExited
        Border label_border = BorderFactory.createMatteBorder(1, 3, 1, 3,new Color(0,0,153));
        LabelExit.setBorder(label_border);
        LabelExit.setForeground(new Color(0,0,153));
    }//GEN-LAST:event_LabelExitMouseExited

    private void TombolKembaliMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TombolKembaliMouseEntered
        // TODO add your handling code here:
        TombolKembali.setBackground(Color.yellow);
        TombolKembali.setForeground(Color.black);
    }//GEN-LAST:event_TombolKembaliMouseEntered

    private void TombolKembaliMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TombolKembaliMouseExited
        // TODO add your handling code here:
        TombolKembali.setBackground(new Color(0,0,153));
        TombolKembali.setForeground(Color.white);
    }//GEN-LAST:event_TombolKembaliMouseExited

    private void TombolSimpanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TombolSimpanMouseEntered
        // TODO add your handling code here:
        TombolSimpan.setBackground(Color.yellow);
        TombolSimpan.setForeground(Color.black);
    }//GEN-LAST:event_TombolSimpanMouseEntered

    private void TombolSimpanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TombolSimpanMouseExited
        // TODO add your handling code here:
        TombolSimpan.setBackground(new Color(0,0,153));
        TombolSimpan.setForeground(Color.white);
    }//GEN-LAST:event_TombolSimpanMouseExited

    private void TombolTelusuriMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TombolTelusuriMouseEntered
        // TODO add your handling code here:
        TombolTelusuri.setBackground(Color.yellow);
        TombolTelusuri.setForeground(Color.black);
    }//GEN-LAST:event_TombolTelusuriMouseEntered

    private void TombolTelusuriMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TombolTelusuriMouseExited
        // TODO add your handling code here:
        TombolTelusuri.setBackground(new Color(0,0,153));
        TombolTelusuri.setForeground(Color.white);
    }//GEN-LAST:event_TombolTelusuriMouseExited

    private void TteleponKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TteleponKeyTyped
        if(Character.isLetter(evt.getKeyChar())){
            evt.consume();
            JOptionPane.showMessageDialog(null, "Must be in number format","Attention",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_TteleponKeyTyped

    private void LabelJudulMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelJudulMouseEntered
        LabelJudul.setForeground(Color.YELLOW);
    }//GEN-LAST:event_LabelJudulMouseEntered

    private void LabelJudulMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelJudulMouseExited
        LabelJudul.setForeground(new Color(0,0,153));
    }//GEN-LAST:event_LabelJudulMouseExited

    MJL.data.Pendaftaran pendaftaran = new Pendaftaran();
    MJL.data.Perusahaan perusahaan = new Perusahaan();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser Dtanggallahir;
    private javax.swing.JLabel Label10;
    private javax.swing.JLabel Label11;
    private javax.swing.JLabel Label12;
    private javax.swing.JLabel Label15;
    private javax.swing.JLabel Label16;
    private javax.swing.JLabel Label17;
    private javax.swing.JLabel Label18;
    private javax.swing.JLabel Label19;
    private javax.swing.JLabel Label2;
    private javax.swing.JLabel Label20;
    private javax.swing.JLabel Label21;
    private javax.swing.JLabel Label22;
    private javax.swing.JLabel Label23;
    private javax.swing.JLabel Label24;
    private javax.swing.JLabel Label25;
    private javax.swing.JLabel Label26;
    private javax.swing.JLabel Label3;
    private javax.swing.JLabel Label4;
    private javax.swing.JLabel Label5;
    private javax.swing.JLabel Label6;
    private javax.swing.JLabel Label7;
    private javax.swing.JLabel Label8;
    private javax.swing.JLabel Label9;
    private javax.swing.JLabel LabelExit;
    private javax.swing.JLabel LabelFoto;
    private javax.swing.JLabel LabelJudul;
    private javax.swing.JLabel LabelMinimize;
    private javax.swing.JLabel LabelNote2;
    private javax.swing.JComboBox<String> Pagama;
    private javax.swing.JComboBox<String> Plulusan;
    private javax.swing.JComboBox<String> Ppernikahan;
    private javax.swing.JComboBox<String> Pperusahaan;
    private javax.swing.JRadioButton Rpria;
    private javax.swing.JRadioButton Rwanita;
    private javax.swing.JTextField Talamat;
    private javax.swing.JTextField Tfoto;
    private javax.swing.JTextField Tnama;
    private javax.swing.JButton TombolKembali;
    private javax.swing.JButton TombolSimpan;
    private javax.swing.JButton TombolTelusuri;
    private javax.swing.JTextField Tpengalaman;
    private javax.swing.JTextField Ttelepon;
    private javax.swing.JTextField Ttempatlahir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label13;
    // End of variables declaration//GEN-END:variables
}